CREATE TABLE IF NOT EXISTS images (
    id                  INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    filename            VARCHAR(255)    NOT NULL,
    original_filename   VARCHAR(255)    NOT NULL,
    filepath            VARCHAR(512)    NOT NULL,
    original_filepath   VARCHAR(512)    NOT NULL,
    thumb_filepath      VARCHAR(512)    NOT NULL,
    filesize            INT UNSIGNED    NOT NULL DEFAULT 0,
    original_filesize   INT UNSIGNED    NOT NULL DEFAULT 0,
    optimized_filesize  INT UNSIGNED    NOT NULL DEFAULT 0,
    optimization_ratio  DECIMAL(5,2)    NOT NULL DEFAULT 0.00,
    width               SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    height              SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    mime_type           VARCHAR(100)    NOT NULL,
    brand_id            INT UNSIGNED    NOT NULL,
    location_id         INT UNSIGNED    NOT NULL,
    uploaded_by         INT UNSIGNED    NOT NULL,
    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at          DATETIME        NULL,
    FOREIGN KEY (brand_id)    REFERENCES brands(id),
    FOREIGN KEY (location_id) REFERENCES locations(id),
    FOREIGN KEY (uploaded_by) REFERENCES users(id),
    INDEX idx_brand_id    (brand_id),
    INDEX idx_location_id (location_id),
    INDEX idx_uploaded_by (uploaded_by),
    INDEX idx_deleted_at  (deleted_at),
    INDEX idx_created_at  (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
